type NumberComparison = {
  name: string;
  count: number;
  image?: string;
};

type NumberComparisons = Array<NumberComparison>;

export const LINES_OF_CODE_FOR_VARIOUS_PROJECTS: NumberComparisons = [
  { name: "Unix v1", count: 4_500 },
  { name: "Photoshop 1.0", count: 128_000 },
  { name: "Quake 3", count: 300_000 },
  { name: "Space Shuttle", count: 400_000 },
  { name: "facebook/react", count: 428_220 },
  { name: "denoland/deno", count: 729_719 },
  { name: "Age of Empires Online", count: 1_200_000 },
  { name: "F-22 Raptor Jet", count: 1_700_000 },
  { name: "rust-lang/rust", count: 1_897_786 },
  { name: "Jurassic Park (according to Nedry)", count: 2_000_000 },
  { name: "Mars Curiosty Rover", count: 2_500_000 },
  { name: "vercel/next.js", count: 1209598 },
  { name: "facebook/react-native", count: 498004 },
  { name: "kubernetes/kubernetes", count: 5361178 },
  { name: "nodejs/node", count: 8365190 },
  { name: "microsoft/TypeScript", count: 2919594 },
  { name: "angular/angular", count: 923978 },
  { name: "apache/spark", count: 1528116 },
  { name: "puppeteer/puppeteer", count: 110222 },
  { name: "sveltejs/svelte", count: 143207 },
  { name: "bitcoin/bitcoin", count: 691645 },
  { name: "apple/swift", count: 2699388 },
  { name: "redis/redis", count: 316232 },
  { name: "twitter/the-algorithm", count: 475305 },
  { name: "vitejs/vite", count: 75504 },
  { name: "reduxjs/redux", count: 397660 },
  { name: "jquery/jquery", count: 50176 },
  { name: "lodash/lodash", count: 23375 },
  { name: "rails/rails", count: 425241 },
  { name: "expressjs/express", count: 20951 },
  { name: "vuejs/vue", count: 74394 },
  { name: "grafana/grafana", count: 1710938 },
  { name: "facebookresearch/llama", count: 1044 },
];

export const WORDS_FOR_FAMOUS_BOOKS = [
  { name: "Les Miserables by Victor Hugo", count: 568751 },
  { name: "War and Peace by Leo Tolstoy", count: 567246 },
  { name: "The Lord of the Rings by J. R. R. Tolkien", count: 564187 },
  { name: "The Count of Monte Cristo by Alexandre Dumas", count: 464162 },
  { name: "Don Quixote by Miguel de Cervantes Saavedra", count: 430269 },
  { name: "David Copperfield by Charles Dickens", count: 360231 },
  { name: "The Brothers Karamazov by Fyodor Dostoyevsky", count: 354098 },
  { name: "Anna Karenina by Leo Tolstoy", count: 353250 },
  { name: "The Decameron by Giovanni Boccaccio", count: 311155 },
  { name: "Ulysses by James Joyce", count: 268170 },
  { name: "The Republic by Plato", count: 220117 },
  { name: "Leviathan by Thomas Hobbes", count: 216349 },
  { name: "Moby Dick by Herman Melville", count: 215839 },
  { name: "Crime and Punishment by Fyodor Dostoyevsky", count: 208016 },
  { name: "The Iliad by Homer", count: 193536 },
  { name: "Jane Eyre by Charlotte Bronte", count: 190339 },
  { name: "Little Women by Louisa May Alcott", count: 189290 },
  { name: "Great Expectations by Charles Dickens", count: 187596 },
  { name: "The Girl with the Dragon Tattoo by Stieg Larsson", count: 184635 },
  { name: "Uncle Tom’s Cabin by Harriet Beecher Stowe", count: 184055 },
  { name: "Dracula by Bram Stoker", count: 165453 },
  { name: "Emma by Jane Austen", count: 163514 },
  { name: "Oliver Twist by Charles Dickens", count: 161712 },
  {
    name: "On the Origin of Species By Means of Natural Selection by Charles Darwin",
    count: 158747,
  },
  { name: "The Da Vinci Code by Dan Brown", count: 144330 },
  { name: "A Tale of Two Cities by Charles Dickens", count: 139605 },
  { name: "The Odyssey by Homer", count: 132694 },
  { name: "Pride and Prejudice by Jane Austen", count: 124713 },
  {
    name: "The Life and Adventures of Robinson Crusoe by Daniel Defoe",
    count: 123936,
  },
  { name: "Sense and Sensibility by Jane Austen", count: 122646 },
  { name: "The Twilight by Stephenie Meyer", count: 120238 },
  { name: "Wuthering Heights by Emily Bronte", count: 119572 },
  { name: "Walden by Henry David Thoreau", count: 118922 },
  { name: "Adventures of Huckleberry Finn by Mark Twain", count: 118804 },
  {
    name: "Thus Spake Zarathustra by Friedrich Wilhelm Nietzsche",
    count: 115632,
  },
  {
    name: "The Confessions of St. Augustine by Bishop of Hippo Saint Augustine",
    count: 114915,
  },
  {
    name: "The Adventures of Sherlock Holmes by Arthur Conan Doyle",
    count: 107605,
  },
  { name: "Gulliver’s Travels by Jonathan Swift", count: 107293 },
  { name: "Anne of Green Gables by L. M. Montgomery", count: 106294 },
  { name: "Grimms’ Fairy Tales by the Grimm Brothers", count: 104228 },
  { name: "A Journal of the Plague Year by Daniel Defoe", count: 98034 },
  { name: "The Scarlet Letter by Nathaniel Hawthorne", count: 86897 },
  { name: "The Secret Garden by Frances Hodgson Burnett", count: 83705 },
  { name: "The Picture of Dorian Gray by Oscar Wilde", count: 82222 },
  { name: "Frankenstein by Mary Wollstonecraft Shelley", count: 78100 },
  {
    name: "Harry Potter and the Sorcerer’s Stone by J. K. Rowling",
    count: 77423,
  },
  { name: "Meditations by Emperor of Rome Marcus Aurelius", count: 75055 },
  { name: "The Adventures of Tom Sawyer by Mark Twain", count: 74772 },
  { name: "The Catcher in the Rye by J. D. Salinger", count: 74144 },
  { name: "Josefine Mutzenbacher by Felix Salten", count: 73567 },
  {
    name: "Baron Trump’s Marvellous Underground Journey by Ingersoll Lockwood",
    count: 72424,
  },
  { name: "Treasure Island by Robert Louis Stevenson", count: 72036 },
  { name: "The Souls of Black Folk by W. E. B. Du Bois", count: 71747 },
  { name: "Dubliners by James Joyce", count: 70693 },
  { name: "The Autobiography by Benjamin Franklin", count: 70229 },
  { name: "The Awakening by Kate Chopin", count: 67286 },
  { name: "Beyond Good and Evil by Friedrich Wilhelm Nietzsche", count: 66835 },
  { name: "The Devil’s Dictionary by Ambrose Bierce", count: 63397 },
  { name: "The War of the Worlds by H. G. Wells", count: 63194 },
  { name: "The Hound of the Baskervilles by Arthur Conan Doyle", count: 62297 },
  { name: "The Kama Sutra of Vatsyayana by Vatsyayana", count: 62155 },
  { name: "Calculus Made Easy by Silvanus P. Thompson", count: 60893 },
  { name: "The Mysterious Affair at Styles by Agatha Christie", count: 59608 },
  { name: "And Then There Were None by Agatha Christie", count: 54324 },
  { name: "The Jungle Book by Rudyard Kipling", count: 54178 },
  { name: "The Prince by Niccolo Machiavelli", count: 52677 },
  {
    name: "Tractatus Logico-Philosophicus by Ludwig Wittgenstein",
    count: 51005,
  },
  { name: "Peter Pan by J. M. Barrie", count: 50844 },
  { name: "A Study in Scarlet by Arthur Conan Doyle", count: 47015 },
  { name: "The Sign of the Four by Arthur Conan Doyle", count: 46164 },
  { name: "Narrative of the Life by Frederick Douglass", count: 44008 },
  { name: "Beowulf by J. Lesslie Hall", count: 43092 },
  { name: "Robert’s Rules of Order by Henry M. Robert", count: 42821 },
  { name: "The Wonderful Wizard of Oz by L. Frank Baum", count: 42636 },
  { name: "Siddhartha by Hermann Hesse", count: 42216 },
  { name: "Heart of Darkness by Joseph Conrad", count: 41597 },
  { name: "The Alchemist, by Paulo Coelho", count: 38871 },
  { name: "Pygmalion by Bernard Shaw", count: 36718 },
  { name: "The Time Machine by H. G. Wells", count: 35530 },
  { name: "The Call of the Wild by Jack London", count: 34964 },
  { name: "A Christmas Carol by Charles Dickens", count: 31650 },
  { name: "A Doll’s House by Henrik Ibsen", count: 29843 },
  { name: "Alice’s Adventures in Wonderland by Lewis Carroll", count: 29610 },
  {
    name: "The Strange Case of Dr. Jekyll and Mr. Hyde by Robert Louis Stevenson",
    count: 28668,
  },
  { name: "Metamorphosis by Franz Kafka", count: 25189 },
  { name: "Common Sense by Thomas Paine", count: 25033 },
  { name: "The Importance of Being Earnest by Oscar Wilde", count: 23760 },
  { name: "Anthem by Ayn Rand", count: 22239 },
  { name: "The Happy Princeby Oscar Wilde", count: 19489 },
  { name: "The Little Prince by Antoine de Saint-Exupery", count: 17121 },
  { name: "A Pickle for the Knowing Ones by Timothy Dexter", count: 17101 },
  { name: "The Prophet by Kahlil Gibran", count: 15800 },
  {
    name: "Southern Horrors – Lynch Law in All Its Phases by Ida B. Wells-Barnett",
    count: 12709,
  },
  { name: "As a Man Thinketh by James Allen", count: 10610 },
  { name: "Ion by Plato", count: 9555 },
  { name: "The Yellow Wallpaper by Charlotte Perkins Gilman", count: 9105 },
  { name: "A Modest Proposal by Jonathan Swift", count: 6535 },
  { name: "The Tale of Peter Rabbit by Beatrix Potter", count: 4058 },
  { name: "The Works of Edgar Allan Poe by Edgar Allan Poe", count: 3971 },
];

export function findClosestNumberComparison(
  num: number,
  comparisons: NumberComparisons = LINES_OF_CODE_FOR_VARIOUS_PROJECTS,
): NumberComparison {
  let closest: NumberComparison = comparisons[0];

  for (const comparison of comparisons) {
    if (Math.abs(comparison.count - num) < Math.abs(closest.count - num)) {
      closest = comparison;
    }
  }

  return closest;
}
